"""update User model with avoiding orphan records and adding free_spins

Revision ID: 1376eb1c23b9
Revises: b038fa5bc64c
Create Date: 2025-10-05 18:23:10.843596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1376eb1c23b9'
down_revision = 'b038fa5bc64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_type'), ['type'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_spins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('free_spins')

    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_type'))

    # ### end Alembic commands ###
